<?php

namespace App\Console\Commands;

use App\Models\AttendanceDocument;
use App\Models\Internship;
use Illuminate\Console\Command;

class TestAutoSaveDocument extends Command
{
    protected $signature = 'test:auto-save-document';
    protected $description = 'Test automatic document saving functionality';

    public function handle()
    {
        $this->info('🔍 Testing Attendance Document Auto-Save Feature...\n');

        // Test 1: Check if Model exists and accessible
        $this->info('Test 1: Checking AttendanceDocument Model...');
        try {
            $count = AttendanceDocument::count();
            $this->info("✓ Model accessible. Total documents: {$count}\n");
        } catch (\Exception $e) {
            $this->error("✗ Error: " . $e->getMessage() . "\n");
            return;
        }

        // Test 2: Check if Service exists
        $this->info('Test 2: Checking AttendanceDocumentService...');
        try {
            $service = new \App\Services\AttendanceDocumentService();
            $this->info("✓ Service accessible\n");
        } catch (\Exception $e) {
            $this->error("✗ Error: " . $e->getMessage() . "\n");
            return;
        }

        // Test 3: Check recent documents with relations
        $this->info('Test 3: Listing recent saved documents...');
        $docs = AttendanceDocument::with(['internship.user', 'generatedBy'])
            ->latest()
            ->limit(5)
            ->get();

        if ($docs->count() > 0) {
            $this->info("✓ Found {$docs->count()} recent documents:\n");
            foreach ($docs as $doc) {
                $this->line("  📄 Document ID: {$doc->document_id}");
                $this->line("  👤 Peserta: " . ($doc->internship->user->name ?? 'N/A'));
                $this->line("  👨‍💼 Generated by: " . ($doc->generatedBy->name ?? 'N/A'));
                $this->line("  📅 Period: {$doc->period_start} to {$doc->period_end}");
                $this->line("  📂 File: {$doc->file_path}");
                $this->line("  🕐 Generated: {$doc->generated_at->format('Y-m-d H:i:s')}\n");
            }
        } else {
            $this->info("ℹ No documents found yet. Run export PDF to create one.\n");
        }

        // Test 4: Check Storage
        $this->info('Test 4: Checking stored files...');
        $storagePath = storage_path('app/attendance_documents');
        if (is_dir($storagePath)) {
            $files = count(array_diff(scandir($storagePath), ['.', '..']));
            $this->info("✓ Storage directory exists with files: {$files}\n");
        } else {
            $this->info("ℹ Storage directory not created yet (will be created on first export)\n");
        }

        // Test 5: Table schema check
        $this->info('Test 5: Checking database table columns...');
        try {
            $columns = \Illuminate\Support\Facades\Schema::getColumnListing('attendance_document');
            $this->info("✓ Table columns:");
            foreach ($columns as $col) {
                $this->line("  - {$col}");
            }
            $this->newLine();
        } catch (\Exception $e) {
            $this->error("✗ Error: " . $e->getMessage() . "\n");
            return;
        }

        $this->info('✅ All tests completed successfully!');
        $this->info('🎯 Next step: Export a PDF from Admin or User panel to trigger auto-save');
    }
}
